# Generated by Django 5.2.5 on 2025-09-12 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zerver", "10002_alter_multiuseinvite_invited_as_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventListener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the event listener", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this listener does"
                    ),
                ),
                (
                    "event_types",
                    models.JSONField(default=list, help_text="List of event types to listen for"),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, help_text="Whether this listener is active"),
                ),
                (
                    "handler_module",
                    models.CharField(
                        help_text="Python module path for the handler", max_length=200
                    ),
                ),
                ("handler_class", models.CharField(help_text="Handler class name", max_length=100)),
                (
                    "handler_config",
                    models.JSONField(default=dict, help_text="Configuration for the handler"),
                ),
                (
                    "user_filter",
                    models.JSONField(blank=True, default=dict, help_text="User filtering criteria"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        blank=True,
                        help_text="Restrict to specific realm (null for all realms)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zerver.realm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Listener",
                "verbose_name_plural": "Event Listeners",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ListenerStats",
            fields=[
                (
                    "listener",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="event_listeners.eventlistener",
                    ),
                ),
                ("total_events_processed", models.BigIntegerField(default=0)),
                ("successful_events", models.BigIntegerField(default=0)),
                ("failed_events", models.BigIntegerField(default=0)),
                ("average_processing_time_ms", models.FloatField(default=0.0)),
                ("last_event_processed_at", models.DateTimeField(blank=True, null=True)),
                ("is_running", models.BooleanField(default=False)),
                ("last_error", models.TextField(blank=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Listener Statistics",
                "verbose_name_plural": "Listener Statistics",
            },
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("event_id", models.BigIntegerField()),
                ("event_data", models.JSONField(help_text="Event payload")),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_time_ms",
                    models.IntegerField(help_text="Processing time in milliseconds"),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("realm_id", models.IntegerField(blank=True, null=True)),
                (
                    "listener",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event_listeners.eventlistener",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Log",
                "verbose_name_plural": "Event Logs",
                "ordering": ["-processed_at"],
                "indexes": [
                    models.Index(
                        fields=["listener", "event_type"], name="event_liste_listene_b8f367_idx"
                    ),
                    models.Index(fields=["processed_at"], name="event_liste_process_630c71_idx"),
                    models.Index(fields=["success"], name="event_liste_success_e6638d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ListenerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listener",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="event_listeners.eventlistener",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listener Configuration",
                "verbose_name_plural": "Listener Configurations",
                "unique_together": {("listener", "key")},
            },
        ),
    ]
