# Generated by Django 5.2.5 on 2025-09-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "10001_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiuseinvite",
            name="invited_as",
            field=models.PositiveSmallIntegerField(default=450),
        ),
        migrations.AlterField(
            model_name="preregistrationuser",
            name="invited_as",
            field=models.PositiveSmallIntegerField(default=450),
        ),
    ]
