# Generated by Django 5.2.5 on 2025-10-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "10004_add_broadcast_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcastnotification",
            name="media_content",
            field=models.JSONField(
                default=dict,
                help_text="Rich media content for template fields (images, videos, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="ai_generated",
            field=models.BooleanField(
                default=False, help_text="Whether this template was generated by AI"
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="ai_prompt",
            field=models.TextField(
                blank=True, default="", help_text="Original AI prompt used to generate template"
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="template_structure",
            field=models.JSONField(
                default=dict,
                help_text="Rich media template structure with blocks (images, videos, buttons, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="template_type",
            field=models.CharField(
                choices=[("text_only", "Text Only"), ("rich_media", "Rich Media")],
                default="text_only",
                help_text="Type of template: text_only or rich_media with media fields",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="content",
            field=models.TextField(
                help_text="Markdown content of the template (for text_only type)"
            ),
        ),
    ]
