# Generated by Django 5.2.5 on 2025-10-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "10005_add_rich_media_template_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="broadcast_template_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="broadcast_template_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
