# Generated by Django 5.2.5 on 2025-10-25 09:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "10003_add_ai_message_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("content", models.TextField(help_text="Markdown content of the template")),
                (
                    "created_time",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("last_edit_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
            options={
                "ordering": ["-last_edit_time"],
                "unique_together": {("realm", "name")},
            },
        ),
        migrations.CreateModel(
            name="BroadcastNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Notification title/subject", max_length=255),
                ),
                ("content", models.TextField(help_text="Markdown content of the notification")),
                (
                    "attachment_paths",
                    models.JSONField(default=list, help_text="List of file attachment paths"),
                ),
                (
                    "sent_time",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("users", "Specific Users"),
                            ("channels", "Channels"),
                            ("broadcast", "Broadcast All"),
                        ],
                        default="users",
                        max_length=20,
                    ),
                ),
                (
                    "target_ids",
                    models.JSONField(
                        default=list, help_text="List of user or channel IDs targeted"
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zerver.notificationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_time"],
            },
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("sent_time", models.DateTimeField(blank=True, null=True)),
                ("delivered_time", models.DateTimeField(blank=True, null=True)),
                ("read_time", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "message_id",
                    models.IntegerField(
                        blank=True, help_text="ID of the actual Zulip message sent", null=True
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="zerver.broadcastnotification",
                    ),
                ),
                (
                    "recipient_channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zerver.stream",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_time"],
                "indexes": [
                    models.Index(
                        fields=["notification", "status"], name="zerver_noti_notific_49e0b7_idx"
                    ),
                    models.Index(
                        fields=["recipient_user", "status"], name="zerver_noti_recipie_6824e9_idx"
                    ),
                ],
                "unique_together": {("notification", "recipient_user", "recipient_channel")},
            },
        ),
    ]
