# Generated by Django 5.2.5 on 2025-09-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "10002_alter_multiuseinvite_invited_as_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="ai_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="archivedmessage",
            name="is_ai_generated",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="ai_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_ai_generated",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
