# Generated by Django 5.2.5 on 2025-10-27 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "10006_add_broadcast_template_data_to_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastButtonClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "button_id",
                    models.CharField(
                        db_index=True, help_text="ID of the button that was clicked", max_length=255
                    ),
                ),
                (
                    "button_type",
                    models.CharField(
                        choices=[("url", "URL Button"), ("quick_reply", "Quick Reply")],
                        default="url",
                        max_length=20,
                    ),
                ),
                (
                    "button_text",
                    models.CharField(help_text="Text displayed on the button", max_length=255),
                ),
                (
                    "button_url",
                    models.TextField(blank=True, help_text="URL for URL-type buttons", null=True),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "broadcast_notification",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the original broadcast notification if available",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="button_clicks",
                        to="zerver.broadcastnotification",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="button_clicks",
                        to="zerver.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_button_clicks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-clicked_at"],
                "indexes": [
                    models.Index(
                        fields=["message", "button_id"], name="zerver_broa_message_bf9bef_idx"
                    ),
                    models.Index(
                        fields=["broadcast_notification", "button_id"],
                        name="zerver_broa_broadca_28ec0b_idx",
                    ),
                    models.Index(
                        fields=["user", "clicked_at"], name="zerver_broa_user_id_8ae6c2_idx"
                    ),
                ],
            },
        ),
    ]
