# Generated by Django 5.2.5 on 2025-09-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "10000_remove_unwanted_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.PositiveSmallIntegerField(db_index=True, default=450),
        ),
    ]
