# Generated by Django 5.2.5 on 2025-09-15 12:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zerver", "10002_alter_multiuseinvite_invited_as_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "call_id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[("video", "Video Call"), ("audio", "Audio Call")], max_length=10
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("ringing", "Ringing"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("declined", "Declined"),
                            ("missed", "Missed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("jitsi_room_name", models.CharField(max_length=255)),
                ("jitsi_room_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("initiated", "Call Initiated"),
                            ("ringing", "Call Ringing"),
                            ("accepted", "Call Accepted"),
                            ("declined", "Call Declined"),
                            ("missed", "Call Missed"),
                            ("ended", "Call Ended"),
                            ("cancelled", "Call Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="zulip_calls_plugin.call",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["state", "created_at"], name="zulip_calls_state_27122d_idx"),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["initiator", "created_at"], name="zulip_calls_initiat_af193f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["recipient", "created_at"], name="zulip_calls_recipie_23756d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["realm", "created_at"], name="zulip_calls_realm_i_2510ab_idx"
            ),
        ),
    ]
