# Generated by Django 5.2.5 on 2025-09-17 09:30

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "10002_alter_multiuseinvite_invited_as_and_more"),
        ("zulip_calls_plugin", "0002_enhance_call_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="call",
            name="zulip_calls_state_27122d_idx",
        ),
        migrations.RemoveIndex(
            model_name="call",
            name="zulip_calls_initiat_af193f_idx",
        ),
        migrations.RemoveIndex(
            model_name="call",
            name="zulip_calls_recipie_23756d_idx",
        ),
        migrations.RemoveIndex(
            model_name="call",
            name="zulip_calls_realm_i_2510ab_idx",
        ),
        migrations.AlterField(
            model_name="call",
            name="call_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="call",
            name="state",
            field=models.CharField(
                choices=[
                    ("calling", "Calling"),
                    ("ringing", "Ringing"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("timeout", "Timeout"),
                    ("ended", "Ended"),
                    ("missed", "Missed"),
                    ("cancelled", "Cancelled"),
                ],
                default="calling",
                max_length=20,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "CREATE INDEX IF NOT EXISTS call_participants_idx ON zulip_calls_plugin_call (sender_id, receiver_id);",
                    reverse_sql="DROP INDEX IF EXISTS call_participants_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="call",
                    index=models.Index(fields=["sender", "receiver"], name="call_participants_idx"),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "CREATE INDEX IF NOT EXISTS call_status_idx ON zulip_calls_plugin_call (state);",
                    reverse_sql="DROP INDEX IF EXISTS call_status_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="call",
                    index=models.Index(fields=["state"], name="call_status_idx"),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "CREATE INDEX IF NOT EXISTS call_created_at_idx ON zulip_calls_plugin_call (created_at);",
                    reverse_sql="DROP INDEX IF EXISTS call_created_at_idx;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="call",
                    index=models.Index(fields=["created_at"], name="call_created_at_idx"),
                ),
            ],
        ),
    ]
